'use client';

import { useState } from 'react';
import { SharedDashboardDateFilter } from '@/components/dashboards/SharedDashboardDateFilter';
import { heatMapSourceQuestions, type HeatMapSegment } from '@/data/heat-map-baseline';
import styles from './HeatMapBaseline.module.css';

type Choice = { value: string; label: string };
const choices = (labels: string[]): Choice[] => labels.map(label => ({ value: label, label }));
function FilterSelect({ label, options, selected, onChange, multiple = false, placeholder = '-Select-' }: { label: string; options: Choice[]; selected: string[]; onChange: (values: string[]) => void; multiple?: boolean; placeholder?: string }) {
  const [open, setOpen] = useState(false);
  const [search, setSearch] = useState('');
  return <div className={styles.filterSelect}><label>{label}</label><button aria-label={label} aria-expanded={open} onClick={() => setOpen(!open)}>{selected.length ? options.filter(option => selected.includes(option.value)).map(option => option.label).join(', ') : placeholder}<span aria-hidden>▾</span></button>{open && <div className={styles.filterOptions}><input aria-label={`Search ${label}`} placeholder="Search" value={search} onChange={event => setSearch(event.target.value)} /><div role="listbox" aria-label={label} aria-multiselectable={multiple}>{options.filter(option => option.label.toLowerCase().includes(search.toLowerCase())).map(option => multiple ? <label key={option.value}><input type="checkbox" aria-label={option.label} checked={selected.includes(option.value)} onChange={() => onChange(selected.includes(option.value) ? selected.filter(value => value !== option.value) : [...selected, option.value])} />{option.label}</label> : <button key={option.value} role="option" aria-selected={selected.includes(option.value)} onClick={() => { onChange([option.value]); setOpen(false); }}>{option.label}</button>)}</div></div>}</div>;
}
const questionChoices = [
  ...['m01', 'm02', 'm03', 'm04'].flatMap(matrix => (matrix === 'm02' ? ['Ease', 'Speed', 'Reliability', 'Support', 'Value', 'Features'] : ['Ease', 'Speed', 'Reliability']).map(title => ({ value: `${matrix}-${title}`, label: title }))),
  ...heatMapSourceQuestions('mixed').filter(question => !question.children && !question.sourceDisclosure && question.code).map(question => ({ value: question.id, label: question.title })),
  ...['Comment Box | nonnumeric exclusion probe', 'Single Row Text | nonnumeric exclusion probe', 'Single Row Text | numeric input probe', 'Email Address | text exclusion probe'].map(label => ({ value: label, label })),
];
const answerChoices = choices(['1 Very poor', '2 Poor', '3 Neutral', '4 Good', '5 Excellent']).map((choice, index) => ({ ...choice, value: String(index + 1) }));
const newCriterion = (block: number): HeatMapSegment['criteria'][number] => ({ option: 'Question', field: '', operator: 'Is', value: '', block });

export function HeatMapFilterEditor({ draft, onChange, onCancel, onSave, widgetFilter = false, error }: { draft: HeatMapSegment; onChange: (draft: HeatMapSegment) => void; onCancel: () => void; onSave: () => void; widgetFilter?: boolean; error?: string }) {
  const [collapsed, setCollapsed] = useState<number[]>([]);
  const patchCriterion = (index: number, patch: Partial<HeatMapSegment['criteria'][number]>) => onChange({ ...draft, criteria: draft.criteria.map((criterion, current) => current === index ? { ...criterion, ...patch } : criterion) });
  const blocks = [...new Set(draft.criteria.map(criterion => criterion.block))];
  return <section className={`${styles.dialog} ${styles.filterDialog}`} role="dialog" aria-modal="true" aria-label={widgetFilter ? 'Create widget filter' : 'Create segment'}><header><h2>{widgetFilter ? 'Create widget filter' : 'Create segment'}</h2><button aria-label="Close filter editor" onClick={onCancel}>×</button></header>
    <input aria-label={widgetFilter ? 'Filter name' : 'Segment name'} placeholder={widgetFilter ? 'Enter filter name' : 'Enter segment name'} value={draft.name} onChange={event => onChange({ ...draft, name: event.target.value })} />
    <FilterSelect label="Response status" options={choices(['All responses', 'Completed', 'Started but not completed', 'Terminates'])} selected={[draft.responseStatus]} onChange={values => onChange({ ...draft, responseStatus: values[0] })} />
    <div className={styles.dateField}><label>Filter by date</label><SharedDashboardDateFilter startDate={draft.from} endDate={draft.to} onChange={range => onChange({ ...draft, from: range.startDate, to: range.endDate })} /></div>
    {!blocks.length && <button className={styles.addCriterion} onClick={() => onChange({ ...draft, criteria: [newCriterion(1)] })}>＋ Add criteria</button>}
    {blocks.map(block => <section className={styles.filterBlock} key={block}><button className={styles.blockHeading} aria-label={`Toggle Block ${block}`} aria-expanded={!collapsed.includes(block)} onClick={() => setCollapsed(collapsed.includes(block) ? collapsed.filter(value => value !== block) : [...collapsed, block])}>Block {block}<span>{draft.criteria.filter(criterion => criterion.block === block).length} condition{draft.criteria.filter(criterion => criterion.block === block).length > 1 ? 's' : ''} ▾</span></button>{!collapsed.includes(block) && draft.criteria.map((criterion, index) => criterion.block !== block ? null : <div className={styles.filterCondition} key={index}><span className={styles.conditionLogic}>{draft.criteria.slice(0, index).some(previous => previous.block === block) ? 'AND' : 'IF'}</span><div className={styles.conditionFields}><FilterSelect label="Option" options={choices(['Question', 'System Variable', 'Geo Location', 'Data Quality', 'Dataset'])} selected={[criterion.option]} onChange={values => patchCriterion(index, { option: values[0], field: '', value: '' })} />{criterion.option === 'Question' ? <><FilterSelect label="Survey question" options={questionChoices} selected={criterion.field ? [criterion.field] : []} onChange={values => patchCriterion(index, { field: values[0], value: '' })} />{criterion.field && <><FilterSelect label="Operator" options={choices(['Is', 'Is not'])} selected={[criterion.operator]} onChange={values => patchCriterion(index, { operator: values[0] })} /><FilterSelect label="Question values" options={criterion.field === 'single' || criterion.field.startsWith('m0') ? answerChoices : []} selected={criterion.value ? criterion.value.split(',') : []} multiple placeholder="Enter your value" onChange={values => patchCriterion(index, { value: values.join(',') })} /></>}</> : <div className={styles.filterSelect}><label>{criterion.option}</label><button disabled>-Select- ▾</button></div>}</div><div className={styles.conditionActions}><button aria-label="Remove criteria" onClick={() => onChange({ ...draft, criteria: draft.criteria.filter((_, current) => current !== index) })}>−</button><button aria-label="Add criteria" onClick={() => onChange({ ...draft, criteria: [...draft.criteria, newCriterion(block)] })}>＋</button></div></div>)}</section>)}
    {!!blocks.length && <button className={styles.addCriterion} onClick={() => onChange({ ...draft, criteria: [...draft.criteria, newCriterion(Math.max(...blocks) + 1)] })}>＋ Add OR condition</button>}
    {error && <p className={styles.filterError} role="alert">{error}</p>}<footer><button onClick={onCancel}>Cancel</button><button className={styles.primary} onClick={onSave}>{widgetFilter ? 'Save' : 'Create'}</button></footer>
  </section>;
}
