'use client';
import {useState} from 'react';
import {useWuShowToast} from '@npm-questionpro/wick-ui-lib';
import {autoMapAnswers,compatibleStackQuestions,type MetricGroup,type StackQuestion} from '@/data/question-stacks';
import {StackButton,StackDialog,StackInput} from './StackControls';
import styles from './Stacks.module.css';
export function MetricGroupEditor({group,questions,names,onSave,onClose}:{group?:MetricGroup;questions:StackQuestion[];surveyId:number;names:string[];onSave:(group:MetricGroup)=>void;onClose:()=>void}){
 const [draft,setDraft]=useState<MetricGroup>(()=>group?structuredClone(group):{id:crypto.randomUUID(),name:'',questionIds:[],labels:[],scores:[],mappings:{}});const [search,setSearch]=useState('');const {showToast}=useWuShowToast();
 const available=compatibleStackQuestions(questions,draft.questionIds).filter(q=>`${q.code} ${q.text}`.toLowerCase().includes(search.toLowerCase()));
 const nameError=names.some(n=>n.trim().toLowerCase()===draft.name.trim().toLowerCase());
 function toggle(q:StackQuestion){if(draft.questionIds.includes(q.id)){const ids=draft.questionIds.filter(id=>id!==q.id);setDraft({...draft,questionIds:ids,...(!ids.length?{labels:[],scores:[],mappings:{}}:{})});return;}
 if(draft.questionIds.length===20){showToast({message:'Only 20 questions can be stacked within a metric group.',variant:'warning'});return;}
 const labels=draft.labels.length?draft.labels:[...q.options!];setDraft({...draft,labels,scores:draft.scores.length?draft.scores:labels.map((_,i)=>i+1),questionIds:[...draft.questionIds,q.id],mappings:{...draft.mappings,[q.id]:autoMapAnswers(q.options!,labels)}});}
 return <StackDialog wide title={group?'Edit metric group':'Add metric group'} onClose={onClose} footer={<><div className={styles.pickerChips}>{draft.questionIds.map(id=>{const q=questions.find(q=>q.id===id);return q&&<button className={styles.chip} key={id} aria-label={`Remove ${q.code}`} onClick={()=>toggle(q)}>{q.code} ×</button>;})}</div><span className={styles.hint}>{draft.questionIds.length} / 20</span><StackButton disabled={draft.questionIds.length<2||!draft.name.trim()||nameError} onClick={()=>onSave({...draft,name:draft.name.trim()})}>{group?'Update':'Add metric group'}</StackButton></>}>
 <div className={styles.form}><StackInput aria-label="Metric group name" placeholder="Metric group name" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/>{nameError&&<p role="alert" className={styles.error}>Use a unique metric group name within this stack.</p>}<div className={styles.toolbar}><StackInput aria-label="Search questions" type="search" placeholder="Search" value={search} onChange={e=>setSearch(e.target.value)}/><span className={styles.hint}>Select 2–20 questions{draft.labels.length?` · ${draft.labels.length} answer options`:''}</span></div><div style={{maxHeight:330,overflow:'auto'}}><table className={styles.table}><thead><tr><th>Select</th><th>Question</th><th>Type</th></tr></thead><tbody>{available.map(q=><tr className={draft.questionIds.includes(q.id)?styles.selected:''} key={q.id}><td><input type="checkbox" aria-label={`Select ${q.code}`} checked={draft.questionIds.includes(q.id)} onChange={()=>toggle(q)}/></td><td><button className={styles.link} onClick={()=>toggle(q)}>{q.code} · {q.text}</button></td><td>{q.type} · {q.options?.length} options</td></tr>)}</tbody></table></div><p className={styles.hint}>Incompatible questions are hidden. Review the answer mappings in the stack editor before saving.</p></div></StackDialog>;
}
