'use client';
import {useState} from 'react';
import {MOCK_SURVEY_FOLDERS,MOCK_SURVEYS,type SurveyListItem} from '@/data/mock-survey-folders';
import {formatSmartDate} from '@/data/mock-utils';
import {StackButton,StackDialog,StackInput} from './StackControls';
import styles from './Stacks.module.css';
export function StackSurveyPicker({single=false,min=1,excluded=[],onClose,onSave,replace=false}:{single?:boolean;min?:number;excluded?:number[];onClose:()=>void;onSave:(surveys:SurveyListItem[])=>void;replace?:boolean}){
 const [selected,setSelected]=useState<number[]>([]);const [folder,setFolder]=useState('my-surveys');const [search,setSearch]=useState('');const [sort,setSort]=useState<'name'|'creationDate'|'completedResponses'>('creationDate');const [reverse,setReverse]=useState(true);
 const rows=MOCK_SURVEYS.filter(s=>s.folderId===folder&&!excluded.includes(s.id)&&s.name.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>{const x=a[sort],y=b[sort];return (typeof x==='number'&&typeof y==='number'?x-y:String(x).localeCompare(String(y)))*(reverse?-1:1);});
 function toggle(id:number){setSelected(v=>v.includes(id)?v.filter(x=>x!==id):single?[id]:[...v,id]);}
 return <StackDialog wide title="Add survey" onClose={onClose} footer={<><div className={styles.pickerChips}>{selected.map(id=><button key={id} className={styles.chip} onClick={()=>toggle(id)} aria-label={`Remove ${MOCK_SURVEYS.find(s=>s.id===id)?.name}`}>{MOCK_SURVEYS.find(s=>s.id===id)?.name} ×</button>)}</div><StackButton disabled={selected.length<min} onClick={()=>onSave(selected.map(id=>MOCK_SURVEYS.find(s=>s.id===id)!))}>{replace?'Update':'Add survey'}</StackButton></>}>
 <div className={styles.surveyPicker}><aside><div className={styles.sourceHeading}>Surveys <span>▾</span></div>{MOCK_SURVEY_FOLDERS.map(f=><button key={f.id} className={folder===f.id?styles.folderActive:''} onClick={()=>setFolder(f.id)}><span className="wm-folder"/> {f.name}</button>)}<button className={folder==='shared'?styles.folderActive:''} onClick={()=>setFolder('shared')}>Shared surveys</button></aside><div className={styles.pickerContent}><StackInput aria-label="Search surveys" placeholder="Search" type="search" value={search} onChange={e=>setSearch(e.target.value)}/><table className={styles.table}><thead><tr><th aria-label="Select"/>{(['name','creationDate','completedResponses'] as const).map((key,i)=><th key={key}><button className={styles.sort} onClick={()=>{setSort(key);setReverse(sort===key?!reverse:false);}}>{['Survey','Created on','Completed responses'][i]} ↕</button></th>)}</tr></thead><tbody>{rows.map(s=><tr key={s.id} className={selected.includes(s.id)?styles.selected:''} onClick={()=>toggle(s.id)}><td><input type={single?'radio':'checkbox'} name="source-survey" checked={selected.includes(s.id)} aria-label={`Select ${s.name}`} onClick={e=>e.stopPropagation()} onChange={()=>toggle(s.id)}/></td><td>{s.name}</td><td>{formatSmartDate(s.creationDate)}</td><td>{s.completedResponses.toLocaleString()}</td></tr>)}</tbody></table>{!rows.length&&<p className={styles.hint}>No surveys found.</p>}</div></div>
 </StackDialog>;
}
